### ISSUE TITLE
Bad results for my images

### ISSUE THREAD

**Issue by ErisGe** [fu123456/Specular_highlight_removal_for_real_world_images#2]
I get bad results by using your code. Is there any reasons caught the results? Maybe because I set the wrong parameters?
![413-diffuse](https://user-images.githubusercontent.com/51659777/148155283-2ecd90a8-683c-4332-b416-c9e97ff4a2d5.png)
![172-diffuse](https://user-images.githubusercontent.com/51659777/148155311-8f1fed85-9329-4408-abc7-5bb8ebe88fde.png)

**Comment by fu123456** [comment]
Hi. Our method is not able to handle strong specular highlight very well especially under which content is missing. Also, please read "demo.m" file. You can adjust the key parameters to try to obtain as much better results as possilble.
[https://github.com/fu123456/Specular_highlight_removal_for_real_world_images/blob/main/demo.m#:~:text=%25%25%20Parameter%20setting,two%20key%20parameters.](url)

**Comment by fu123456** [comment]
More specular highlight removal methods can be found here https://github.com/vitorsr/SIHR . You can use these code to address your images. Maybe you can find a method you want which can produce good results.

**Comment by ErisGe** [comment]
Thank you very much! 
I will try these method.
